### ISSUE TITLE
PiPackages will not install software for a second user.

### ISSUE THREAD

**Issue by ruchg** [raspberrypi-ui/pipackage#1]
PiPackages version 0.1.0

Authentication window pops up and the Identity pull down is not updated with the Identity of the second user.

A quick check of PackageKit did not turn up anything similar.

Steps to reproduce:
    • Start with bare metal
        ◦ Prepare 64GB SD card by formatting FAT32
        ◦ Unzip NOOBS v2.9.0 onto SD card.

    • Install fresh SD card and power up
        ◦ Once up, have NOOBS install Raspbian, selecting English (US) language and keyboard
        ◦ Automatic Reboot
        ◦ First Boot Setup
            ▪ Location 
            ▪ New **pi** password
            ▪ Skip WiFi
            ▪ Update Software
            ▪ Reboot

    • Secure
        ◦ Add another user 
            ▪ _sudo_ _adduser_ <new_user>
        ◦ Give new user sudo privlidges
            ▪ _sudo_ _adduser_ <new_user> _sudo_
        ◦ Change root password
            ▪ __sudo_ _passwd_ _root__
        ◦ require password for sudo
            ▪ __sudo_ _nano_ _/etc/sudoers.d/010_pi-nopasswd__
                • change:   pi ALL=(ALL) PASSWD: ALL  and save
        ◦ Reboot

    • Autologin into pi account
        ◦ Menu → Preferences → Add / Remove Software
            ▪ Search for _zim,_ once located, place a check mark adjacent to the box icon
            ▪ press Apply
        ◦ Authentication window pops up
            ▪ Identity **pi**
            ▪ Password **<new_password>**
        ◦ Package is installed.
        ◦ Shutdown Add / Remove Software

    • Expire pi account
        ◦ from Terminal window __sudo_ _usermod_ -L -e 1 pi_
    • Reboot

    • Cannot log in as pi, so log in using <new_user> credentials
        ◦ Menu → Preferences → Add / Remove Software
        ◦ search for _emacs,_ once located, place a check mark adjacent to the box icon
        ◦ press Apply
        ◦ Authentication window pops up
            ▪ Identity: **pi** or **root** no <new_user> available in pull down list
            ▪ Will not take pi credentials

    • Cancel out Add / Remove Software window
    • open Terminal
        ◦ _sudo apt-get update_ (enter <new_user> password when challenged)
        ◦ __sudo_ apt-get upgrade_ 
        ◦ _sudo apt-get install emacs_
        ◦ install begins

**Comment by spl237** [comment]
Interesting - not seen that happen, I'll do some testing this week. Thank you so much for the very detailed description - it'll make my life much easier!

**Comment by spl237** [comment]
OK, have repeated this locally. It looks as if it's a PolicyKit issue - for some reason when pi-packages makes calls to PolicyKit, it always does so as the "pi" user, so something may be hard-coded somewhere; it's either in the app itself or in the PolicyKit defaults somewhere. I'll have a dig around and try to fix it.

**Comment by spl237** [comment]
OK, I've found the problem and the fix.

PolicyKit on the default Raspbian install is set up to allow only two possible authentication sources; the pi user and root. If you add another user, in addition to adding this user to various groups (such as sudo, as you are doing above), you need to add it to the list of authentication sources in polkit.

If you look in the file /etc/polkit-1/localauthority.conf.d/60-desktop-policy.conf, you will see the following:

[Configuration]
AdminIdentities=unix-user:pi;unix-user:0

You need to amend this to add your new user, so if your new user is called newuser, this line should become:

AdminIdentities=unix-user:pi;unix-user:newuser;unix-user:0

You will then see newuser offered as an option in the authentication dialog box when you try to install with pipackage, and it will accept that user's password - I've just tried this and it works for me.

I don't think there is any way around this - there are various bits of housekeeping required when adding a new user, and this is one of them. We may at some point add a GUI utility to manage adding and removing users, in which case we can add this to the list of things it will need to do!
