### ISSUE TITLE
Unreadable text

### ISSUE THREAD

**Issue by chrishollis** [raspberrypi-ui/pipackage#10]
The package name and version of the currently selected item is invisible due to a clash in colours. When selecting a package, the description text colour changes from black to white, but the text below is not changed to a suitable colour and disappears.

![pipackage_text_issue](https://github.com/raspberrypi-ui/pipackage/assets/155904444/5f3147ba-c3d7-4b21-91ec-341ccc3824f4)

**Comment by spl237** [comment]
Fixed for next release - should be in apt in the next few days.
