### ISSUE TITLE
i18n of the 'Options' menu

### ISSUE THREAD

**Issue by emanueleg** [raspberrypi-ui/pipackage#4]
Hi, it seems the label for the 'Options' menu is hardcoded and cannot be localized
https://github.com/raspberrypi-ui/pipackage/blob/13cb547d41e6b39ac9634a8e362a81d4a6518f22/src/gpk-application.c#L3316

**Comment by spl237** [comment]
To be honest, I wouldn't bother localising this particular application - it is probably going to be replaced with something like Synaptic in the future.

**Comment by emanueleg** [comment]
Fine, thanks for the info!
