### ISSUE TITLE
Bad text contrast when using PixFlat dark theme

### ISSUE THREAD

**Issue by Botspot** [raspberrypi-ui/pipackage#6]
Many people are fans of dark themes, and RPi users are no exception. I recently found that no matter what dark theme I used, the pi-packages loading dialog uses white text on a white background. When using a light GTK theme, the dialog is black text on a white background.

Same results with 3 dark GTK themes I tried: `PiXflat:dark`, `Adwaita-Dark`, and `Windows-11-Dark`.

Ideally, the background for this dialog should follow `bg_color`, as assigned in the GTK theme. I presume it is a hardcoded color, at the moment.

To reproduce: Using latest PiOS Bullseye32-bit, fully updated.
Command I ran:
```
GTK_THEME=PiXflat:dark pi-packages
```
Output in the terminal:
```
(pi-packages:10456): Gtk-CRITICAL **: 00:43:47.829: gtk_widget_get_style_context: assertion 'GTK_IS_WIDGET (widget)' failed

(pi-packages:10456): Gtk-CRITICAL **: 00:43:47.829: gtk_style_context_add_class: assertion 'GTK_IS_STYLE_CONTEXT (context)' failed
```
Screenshot:
![2022-10-03-005109_1920x1080_scrot](https://user-images.githubusercontent.com/54716352/193509556-638c5236-7a2c-4dc7-a76c-01dbf080b237.png)

**Comment by spl237** [comment]
This is fixed with our own dark theme.
